version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=dahilayanSecret
      - POSTGRES_USER=dahilayanUser
      - POSTGRES_DB=nest-dahilayan
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
