version: '3.9'
services:
  dahilyan-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=dahilayanSecret
      - POSTGRES_USER=dahilayanUser
      - POSTGRES_DB=nest-dahilayan
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
